package info.longshore.sudoku.gui;

import info.longshore.sudoku.domain.ConstraintPuzzleCollection;
import info.longshore.sudoku.domain.SudokuPuzzle;
import org.jdesktop.application.Action;

import javax.swing.*;

public class NewCollectionDialog extends javax.swing.JDialog {

  /**
   * Creates new form NewCollectionDialog
   */
  public NewCollectionDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel2 = new javax.swing.JLabel();
    nameTextField = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    typeComboBox = new javax.swing.JComboBox();
    jButton2 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(info.longshore.sudoku.gui.SudokuApplication.class).getContext().getResourceMap(NewCollectionDialog.class);
    setTitle(resourceMap.getString("Form.title")); // NOI18N
    setName("Form"); // NOI18N
    setResizable(false);
    addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        NewCollectionDialog.this.keyPressed(evt);
      }
    });

    jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
    jLabel2.setName("jLabel2"); // NOI18N

    nameTextField.setText(resourceMap.getString("nameTextField.text")); // NOI18N
    nameTextField.setName("nameTextField"); // NOI18N
    nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        NewCollectionDialog.this.keyPressed(evt);
      }
    });

    javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(info.longshore.sudoku.gui.SudokuApplication.class).getContext().getActionMap(NewCollectionDialog.class, this);
    jButton1.setAction(actionMap.get("createNewCollection")); // NOI18N
    jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
    jButton1.setName("jButton1"); // NOI18N
    jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        jButton1KeyPressed(evt);
      }
    });

    jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
    jLabel1.setName("jLabel1"); // NOI18N

    typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Sudoku"}));
    typeComboBox.setName("typeComboBox"); // NOI18N
    typeComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        NewCollectionDialog.this.keyPressed(evt);
      }
    });

    jButton2.setAction(actionMap.get("close")); // NOI18N
    jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
    jButton2.setName("jButton2"); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
              .addGap(13, 13, 13)
              .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
              .addContainerGap()
              .addComponent(jLabel2)))
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(typeComboBox, 0, 178, Short.MAX_VALUE)
            .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGap(11, 11, 11)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2))
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel1)
            .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton2))
          .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton1KeyPressed

  private void keyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyPressed
    // TODO add your handling code here:
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
      createNewCollection();
    }
  }//GEN-LAST:event_keyPressed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        NewCollectionDialog dialog = new NewCollectionDialog(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  @Action
  public void close() {
    nameTextField.setText("");
    this.setVisible(false);
  }

  @Action
  public void createNewCollection() {
    // Validation is pretty simple here, so just explicit code...

    String nameText = nameTextField.getText();
    if (nameText.equals("")) {
      JOptionPane.showMessageDialog(this, "Enter a name for the collection.", "Missing Name", JOptionPane.ERROR_MESSAGE);
      nameTextField.requestFocus();
    } else if (SudokuApplication.getApplication().getApplicationModel().collectionWithNameExists(nameText)) {
      JOptionPane.showMessageDialog(this, "A collection with that name already exists.", "Collection Exists", JOptionPane.ERROR_MESSAGE);
      nameTextField.selectAll();
      nameTextField.requestFocus();
    } else {
      ConstraintPuzzleCollection cpc = new ConstraintPuzzleCollection(nameTextField.getText(), SudokuPuzzle.class, SudokuPuzzle.getRuleset());
      SudokuApplication.getApplication().getApplicationView().openCollection(cpc);
      setVisible(false);
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JTextField nameTextField;
  private javax.swing.JComboBox typeComboBox;
  // End of variables declaration//GEN-END:variables

}
